model_list:
  - model_name: vertex_ai/gemini-1.5-pro
    litellm_params:
      model: vertex_ai/gemini-1.5-pro

general_settings:
  vertex_project: autogenstudio-knn3
  vertex_location: asia-southeast1
  server_workers: ${SERVER_WORKERS:-4}  # Default to 4 if not set
